http:
  host: "127.0.0.1"
  port: "80"
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

cache:
  ttl: 3600s

jwt:
  accessTokenTTL: 15m
  refreshTokenTTL: 30m
  verificationCodeLength: 10

limiter:
  rps: 10
  burst: 2
  ttl: 10m

postgres:
  username: "postgres"
  dataBaseName: "crm"
  host: "127.0.0.1"
  port: "5432"
  ssl: 0
  debug: 0

user:
  passwordTTL: 10m